name: Release

on:
  release:
    types: [created, published]

env:
  CARGO_TERM_COLOR: always

jobs:
  release-linux:
    runs-on: ubuntu-latest
  
    steps:
    - name: Install latest nightly
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: nightly
    - name: Build binary
      run: cargo build --release
    - name: Upload to Release
      uses: Shopify/upload-to-release@v2.0.0
      with:
        name: eve-vulcain.linux.x86_64 
        path: target/release/eve-vulcain 
        repo-token: ${{ secrets.GITHUB_TOKEN }} 
  
  release-windows:
    runs-on: windows-latest
    if: github.event_name == 'release'

    steps:
    - name: Install latest nightly
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: nightly
    - name: Build binary
      run: cargo build --release
    - name: Upload to Release
      uses: Shopify/upload-to-release@v2.0.0
      with:
        name: eve-vulcain.windows.x86_64.exe
        path: target/release/eve-vulcain
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    

