name: Release

on:
  push:
    tags:
      - '*'

env:
  CARGO_TERM_COLOR: always

jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: eve-vulcain
            asset_name: eve-vulcain-linux-x86_64
          - os: windows-latest
            artifact_name: eve-vulcain.exe
            asset_name: eve-vulcain-windows-x86_64
  
    steps:
    - uses: actions/checkout@v3
    - name: Install latest nightly
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: nightly
    - name: Build binary
      run: cargo build --release
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: target/release/${{ matrix.artifact_name }}
        asset_name: ${{ matrix.asset_name }}
        tag: ${{ github.ref }}
