name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install latest nightly
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: nightly
        components: rustfmt, clippy
    - name: Lint
      run: cargo clippy
    - name: Build
      run: cargo check --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Verify formatting
      run: cargo fmt --check

  release-linux:
    runs-on: ubuntu-latest
    needs: check
    if: github.event_name == 'release'

    steps:
    - name: Install latest nightly
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: nightly
    - name: Build binary
      run: cargo build --release
    - name: Upload to Release
      uses: Shopify/upload-to-release@v2.0.0
      with:
        name: eve-vulcain.linux.x86_64 
        path: target/release/eve-vulcain 
        repo-token: ${{ secrets.GITHUB_TOKEN }} 
  
  release-windows:
    runs-on: windows-latest
    needs: check
    if: github.event_name == 'release'

    steps:
    - name: Install latest nightly
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: nightly
    - name: Build binary
      run: cargo build --release
    - name: Upload to Release
      uses: Shopify/upload-to-release@v2.0.0
      with:
        name: eve-vulcain.windows.x86_64.exe
        path: target/release/eve-vulcain
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    
