name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install latest nightly
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: nightly
        components: rustfmt, clippy
    - name: Lint
      run: cargo clippy
    - name: Build
      run: cargo check --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Verify formatting
      run: cargo fmt --check

    - name: Install latest nightly
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: nightly
        targets: x86_64-unknown-linux-gnu,x86_64-pc-windows-msvc
        components: rustfmt, clippy
    - name: Build Linux binary
      run: cargo build --release --target x86_64-unknown-linux-gnu
    - name: Build Windows binary
      run: cargo build --release --target x86_64-pc-windows-msvc
  #release:
   # runs-on: ubuntu-latest
   # needs: check
   # if: github.event_name == 'release'
    
   # steps:
    

